#%%
import icechunk
import xarray as xr

# %%
ds = xr.open_dataset("/home/mirico/git/actions/tests/data/small_data.nc")
# %%
ds.__str__()
#  '<xarray.Dataset> Size: 5MB\nDimensions:                            (timestamp: 100, fitted_measurement: 6,\n                                        fitted_measurement_duplicate: 6,\n                                        diagnostics_am_scale_sample: 0,\n                                        diagnostic_sample: 1500, retro: 14,\n                                        settings_id: 14, sample: 600,\n                                        high_res_timestamp: 100)\nCoordinates: (12/15)\n    measurement_validity               (timestamp) int32 400B ...\n  * diagnostic_sample                  (diagnostic_sample) int64 12kB 0 ... 1499\n  * diagnostics_am_scale_sample        (diagnostics_am_scale_sample) int64 0B \n  * fitted_measurement                 (fitted_measurement) int32 24B 0 1 ... 5\n  * fitted_measurement_duplicate       (fitted_measurement_duplicate) int32 24B ...\n  * retro                              (retro) int32 56B 612 613 614 ... 624 625\n    ...                                 ...\n    retro_longitude                    (retro) float32 56B ...\n    retro_name                         (retro) |S100 1kB ...\n  * sample                             (sample) int32 2kB 0 1 2 ... 597 598 599\n  * settings_id                        (settings_id) int64 112B 950 951 ... 963\n  * timestamp                          (timestamp) datetime64[ns] 800B 2025-0...\n  * high_res_timestamp                 (high_res_timestamp) datetime64[ns] 800B ...\nData variables: (12/68)\n    c0                                 (timestamp) float64 800B ...\n    c0_stderr                          (timestamp) float64 800B ...\n    c1                                 (timestamp) float64 800B ...\n    c1_stderr                          (timestamp) float64 800B ...\n    c2                                 (timestamp) float64 800B ...\n    c2_stderr                          (timestamp) float64 800B ...\n    ...                                 ...\n    bearing                            (high_res_timestamp) float64 800B ...\n    sonictemp                          (high_res_timestamp) float64 800B ...\n    speed                              (high_res_timestamp) float64 800B ...\n    windx                              (high_res_timestamp) float64 800B ...\n    windy                              (high_res_timestamp) float64 800B ...\n    windz                              (high_res_timestamp) float64 800B ...\nAttributes: (12/14)\n    Conventions:          CF-1.6\n    creator_institution:  Mirico\n    date_created:         2025-03-16T00:41:18\n    featureType:          timeSeries\n    fitted_measurements:  ch4 h2o shift c0 c1 c2\n    gas_id:               3\n    ...                   ...\n    l0_creation:          2025-03-16T00:14:46Z 2025-03-16T00:39:52Z\n    processing_level:     L1\n    processor_name:       clads\n    processor_version:    5.5.10\n    project:              RENUGS\n    project_id:           30'

# %%
